"""Update User class props to match Flask LoginManager interface

Revision ID: 433507baa94e
Revises: 7d84975a0edc
Create Date: 2024-02-13 09:26:03.466971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433507baa94e'
down_revision = '7d84975a0edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_authenticated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=True))
        batch_op.drop_column('authenticated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authenticated', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('is_anonymous')
        batch_op.drop_column('is_authenticated')

    # ### end Alembic commands ###
